version: '2.0'
services:
  # builds lambda package
  build:
    build: "https://github.com/nyxiative/lambda-rust.git"
    volumes:
    - .:/code
    - $HOME/.cargo/registry:/root/.cargo/registry
    environment:
    - BIN=lambda